# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='avatar_url',
            new_name='avatarUrl',
        ),
    ]
