# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_auto_20160114_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='creationDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='creationDate',
            field=models.DateField(),
        ),
    ]
