# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0003_auto_20160114_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='merges',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
