# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0004_auto_20160114_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='contributor',
            name='url',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='issue',
            name='url',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='url',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(max_length=512),
        ),
    ]
