# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0005_auto_20160402_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['contributions']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['creationDate']},
        ),
        migrations.AlterModelOptions(
            name='pullrequest',
            options={'ordering': ['creationDate']},
        ),
    ]
