# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0006_auto_20160408_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['-contributions']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-creationDate']},
        ),
        migrations.AlterModelOptions(
            name='pullrequest',
            options={'ordering': ['-creationDate']},
        ),
    ]
